worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # SERVIDOR HTTPS (Cadeado Verde)
    server {
        listen       443 ssl;
        server_name  10.4.30.2 localhost;

        ssl_certificate      "../certs/certificate.crt";
        ssl_certificate_key  "../certs/private.key";

        # --- REDIRECIONAMENTO DE SEGURANÇA ---
        # Se alguém acessar a raiz (https://10.4.30.2/), manda direto para o frontend
        location = / {
            return 301 https://$host/frontend/;
        }

        # --- ROTA DO FRONTEND (REPASSE PARA O FLASK) ---
        # Aqui ele vai pegar o que está no seu Flask em :8000/frontend
        location /frontend/ {
            proxy_pass http://127.0.0.1:8000/frontend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # --- ROTA DA API (REPASSE PARA O FLASK) ---
        # Supondo que suas buscas de produto comecem com /api ou /search
        # Ajuste o prefixo conforme as rotas que você criou no seu Blueprint
        location /search {
            proxy_pass http://127.0.0.1:8000/search;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/ {
            proxy_pass http://127.0.0.1:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
}
    }

    # Redirecionamento de HTTP para HTTPS
    server {
        listen 80;
        server_name 10.4.30.2 localhost;
        return 301 https://$host$request_uri;
    }
}